name: Build with Docker and Deploy to cPanel via FTP
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - name: Build Docker Image
        run: |
          docker build -t my-app .
 
      - name: Extract Build Files from Docker
        run: |
          docker create --name temp_container my-app
          docker cp temp_container:/var/www/html ./build_output
          docker rm temp_container
 
      - name: Clean unwanted folders from build_output
        run: |
          rm -rf ./build_output/vendor
          rm -rf ./build_output/.git
          rm -f ./build_output/.gitignore
          rm -f ./build_output/.gitattributes
 
      - name: Debug secrets (for troubleshooting only, remove in production)
        run: |
          echo "Host: ${{ secrets.FTP_HOST }}"
          echo "Username: ${{ secrets.FTP_USERNAME }}"
          echo "Password is set: ${{ secrets.FTP_PASSWORD != '' }}"
 
      - name: Deploy to cPanel via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 145.79.212.228
          username: 'u378554361.hr-portal.fableadtech.in'
          password: '!FIw4bGC5yF$2J]d'
          server-dir: /public_html/
          local-dir: ./build_output/
          # timeout: 600000
          protocol: ftps
          port: 21
          exclude: |
            **/.git*
            **/vendor/**
            **/writable/**
            **/system/**
            **/uploads/**
            **/public/vendors/**
